name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/backend.yml"

  pull_request:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t etwms-backend ./server